#!/usr/bin/env bash
set -euo pipefail

# Script to explore alternative clock sources for PiStorm on Pi5
# Focuses on using PIO (Programmable IO) instead of GPCLK0

echo "[pio-clock-alt] Exploring alternative clock sources for PiStorm on Pi5"
echo ""
echo "KEY FINDING from RP1 peripherals document:"
echo "- GPIO4 can function as PIO[4] (function select a7)"
echo "- GPIO4 can function as GPCLK[0] (function select a0) - current approach"
echo "- PIO blocks are identical to RP2040 (with doubled FIFO depth)"
echo "- PIO has single-cycle bus access from RP1 Cortex-M3 management processors"
echo ""
echo "PIO ADVANTAGES over GPCLK0:"
echo "- Not subject to kernel GPCLK0 frequency limits (100MHz cap)"
echo "- Can generate precise, high-frequency signals (up to 200MHz+)"
echo "- Designed for custom timing patterns and waveforms"
echo "- Direct access from Cortex-M3 processors"
echo ""
echo "PIO-BASED 200MHz CLOCK APPROACH:"
echo "1. Program one of the PIO state machines to generate 200MHz clock pattern"
echo "2. Route the output to GPIO4 (function select a7 for PIO[4])"
echo "3. Use the dual Cortex-M3 processors on RP1 to run the PIO firmware"
echo ""
echo "IMPLEMENTATION OPTIONS:"
echo ""
echo "Option 1: Use existing PWM-PIO overlay (if available):"
echo "  sudo dtoverlay pwm-pio,gpio=4"
echo "  # This uses PIO to generate PWM, may achieve high frequencies"
echo ""
echo "Option 2: Custom PIO firmware (advanced):"
echo "  - Write PIO assembly code to generate 200MHz square wave"
echo "  - Load firmware to one of RP1's Cortex-M3 processors"
echo "  - Configure PIO state machine to output on GPIO4"
echo ""
echo "Option 3: Use alternative system clocks:"
echo "  - RP1 has Core PLL running at 2GHz (divided to 200MHz clk_sys)"
echo "  - Audio PLL at 1.536GHz for audio clocks"
echo "  - Could potentially route these through GPIO muxing"
echo ""
echo "RECOMMENDED NEXT STEPS:"
echo "1. Try PWM-PIO overlay as immediate test:"
echo "   sudo dtoverlay -d ./pi5/gpclk0 pistorm-gpclk0  # Keep GPCLK0 setup"
echo "   sudo dtoverlay pwm-pio,gpio=4                 # Add PIO-based PWM"
echo "2. Test with emulator using both clock sources"
echo "3. If PWM-PIO works, investigate custom PIO firmware for precise 200MHz"
echo ""
echo "Note: The HDMI clock runs at just over 200MHz, proving the hardware"
echo "      is capable of these frequencies - it's just the GPCLK0 driver"
echo "      that limits it to 100MHz."