#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# PiStorm backend benchmark harness
#
# Purpose:
# - Generate per-case config files that swap only PiStorm backend/timing knobs.
# - Run optional quick sanity checks (truth test, buptest).
# - Launch emulator per case and wait for exit (or external killall).
# - Log all case metadata and return codes for later comparison.
#
# Typical usage:
#   ./tools/pistorm-backend-harness.sh
#   ./tools/pistorm-backend-harness.sh --userspace-divs 6,8 --userspace-wr 2,4 --userspace-rd 2,4
#   ./tools/pistorm-backend-harness.sh --run-buptest --buptest-kb 512

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_CFG="${ROOT_DIR}/default.cfg"
EMU_BIN="${ROOT_DIR}/emulator"
TRUTH_BIN="${ROOT_DIR}/pistorm_truth_test"
BUPTEST_BIN="${ROOT_DIR}/buptest"

RUN_TRUTH=1
TRUTH_SAMPLES=1000
RUN_BUPTEST=0
BUPTEST_KB=512
RUN_EMULATOR=1
AUTO_CONTINUE=0
FORCE_CONTINUE_ON_FAIL=0

BACKENDS=("kernel" "userspace")
USER_DIVS=(6 8 10)
USER_WRS=(2 4 8)
USER_RDS=(2 4 8)
EMU_EXTRA_ARGS=()

RUN_TS="$(date +%Y%m%d-%H%M%S)"
RUN_DIR="${ROOT_DIR}/logs/backend-harness-${RUN_TS}"
RESULTS_CSV="${RUN_DIR}/results.csv"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

warn() {
  echo "WARN: $*" >&2
}

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --base-config PATH         Base config to clone and patch per case (default: ${BASE_CFG})
  --kernel-only              Run only kernel backend case
  --userspace-only           Run only userspace backend cases
  --userspace-divs LIST      Comma-separated GPCLK divisors (default: 6,8,10)
  --userspace-wr LIST        Comma-separated WR stretch values (default: 2,4,8)
  --userspace-rd LIST        Comma-separated RD stretch values (default: 2,4,8)
  --no-truth                 Skip pistorm_truth_test
  --truth-samples N          Truth-test sample count (default: 1000)
  --run-buptest              Run buptest before emulator for each case
  --buptest-kb N             buptest size in KB (default: 512)
  --no-emulator              Do not launch emulator (only prechecks/logging)
  --auto                     Do not prompt before each case
  --continue-on-fail         Keep sweeping even if truth/buptest fails
  --emu-arg ARG              Extra arg passed to emulator (repeatable)
  -h, --help                 Show this help

Examples:
  $0
  $0 --userspace-divs 6,8 --userspace-wr 2,4 --userspace-rd 2,4
  $0 --run-buptest --buptest-kb 512 --continue-on-fail
EOF
}

as_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

run_unprivileged() {
  if [[ "$(id -u)" -eq 0 && -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    sudo -u "${SUDO_USER}" -- "$@"
  else
    "$@"
  fi
}

parse_csv_u32_list() {
  local raw="$1"
  local token
  local out=()

  raw="${raw// /}"
  IFS=',' read -r -a out <<< "${raw}"
  if [[ "${#out[@]}" -eq 0 ]]; then
    die "Empty list: ${raw}"
  fi

  for token in "${out[@]}"; do
    if [[ ! "${token}" =~ ^[0-9]+$ ]]; then
      die "Invalid numeric token '${token}' in list '${raw}'"
    fi
  done

  echo "${out[*]}"
}

case_key() {
  local backend="$1"
  local div="$2"
  local wr="$3"
  local rd="$4"
  if [[ "${backend}" == "kernel" ]]; then
    echo "backend=kernel"
  else
    echo "backend=userspace div=${div} wr=${wr} rd=${rd}"
  fi
}

write_case_cfg() {
  local out_cfg="$1"
  local backend="$2"
  local div="$3"
  local wr="$4"
  local rd="$5"

  {
    echo "# auto-generated by tools/pistorm-backend-harness.sh"
    echo "# run: ${RUN_TS}"
    echo "pistorm ${backend}"
    if [[ "${backend}" == "userspace" ]]; then
      echo "pistorm-gpclk-src 5"
      echo "pistorm-gpclk-div ${div}"
      echo "pistorm-mmio-wr-stretch ${wr}"
      echo "pistorm-mmio-rd-stretch ${rd}"
    fi
    echo
    awk '
      /^[[:space:]]*#/ { print; next }
      /^[[:space:]]*$/ { print; next }
      {
        key = $1
        if (key == "pistorm" ||
            key == "pistorm-gpclk-src" ||
            key == "pistorm-gpclk-div" ||
            key == "pistorm-mmio-wr-stretch" ||
            key == "pistorm-mmio-rd-stretch") {
          next
        }
        print
      }
    ' "${BASE_CFG}"
  } > "${out_cfg}"
}

csv_escape() {
  local s="$1"
  s="${s//\"/\"\"}"
  printf "\"%s\"" "${s}"
}

prepare_backend() {
  local backend="$1"

  as_root killall -9 emulator >/dev/null 2>&1 || true
  sleep 0.2

  if [[ "${backend}" == "userspace" ]]; then
    as_root rmmod pistorm >/dev/null 2>&1 || true
  else
    if ! as_root modprobe pistorm >/dev/null 2>&1; then
      warn "modprobe pistorm failed (kernel case may fail if /dev/pistorm unavailable)"
    fi
  fi
}

run_case() {
  local idx="$1"
  local backend="$2"
  local div="$3"
  local wr="$4"
  local rd="$5"
  local case_dir="${RUN_DIR}/case-$(printf '%03d' "${idx}")"
  local cfg="${case_dir}/test.cfg"
  local meta="${case_dir}/meta.txt"
  local truth_log="${case_dir}/truth.log"
  local buptest_log="${case_dir}/buptest.log"
  local emu_log="${case_dir}/emulator.log"
  local note=""
  local rc_truth=0
  local rc_buptest=0
  local rc_emu=0
  local start_ts
  local end_ts

  mkdir -p "${case_dir}"
  write_case_cfg "${cfg}" "${backend}" "${div}" "${wr}" "${rd}"

  {
    echo "case_index=${idx}"
    echo "backend=${backend}"
    echo "div=${div}"
    echo "wr=${wr}"
    echo "rd=${rd}"
    echo "config=${cfg}"
  } > "${meta}"

  echo
  echo "=== Case $(printf '%03d' "${idx}") :: $(case_key "${backend}" "${div}" "${wr}" "${rd}") ==="
  echo "Config: ${cfg}"

  if [[ "${AUTO_CONTINUE}" -eq 0 ]]; then
    read -r -p "Press Enter to start this case (or Ctrl+C to stop)... " _
  fi

  prepare_backend "${backend}"
  start_ts="$(date -Iseconds)"

  if [[ "${RUN_TRUTH}" -eq 1 ]]; then
    set +e
    as_root "${TRUTH_BIN}" -c "${cfg}" "${TRUTH_SAMPLES}" > "${truth_log}" 2>&1
    rc_truth=$?
    set -e
    echo "[case $(printf '%03d' "${idx}")] truth rc=${rc_truth} log=${truth_log}"
    if [[ "${rc_truth}" -ne 0 && "${FORCE_CONTINUE_ON_FAIL}" -eq 0 ]]; then
      die "truth test failed for case $(printf '%03d' "${idx}")"
    fi
  fi

  if [[ "${RUN_BUPTEST}" -eq 1 ]]; then
    set +e
    as_root "${BUPTEST_BIN}" -c "${cfg}" "${BUPTEST_KB}" > "${buptest_log}" 2>&1
    rc_buptest=$?
    set -e
    echo "[case $(printf '%03d' "${idx}")] buptest rc=${rc_buptest} log=${buptest_log}"
    if [[ "${rc_buptest}" -ne 0 && "${FORCE_CONTINUE_ON_FAIL}" -eq 0 ]]; then
      die "buptest failed for case $(printf '%03d' "${idx}")"
    fi
  fi

  if [[ "${RUN_EMULATOR}" -eq 1 ]]; then
    echo "[case $(printf '%03d' "${idx}")] launching emulator; run SSSpeed056/chip tests, then exit emulator or run: sudo killall -9 emulator"
    set +e
    run_unprivileged "${EMU_BIN}" --config-file "${cfg}" "${EMU_EXTRA_ARGS[@]}" > "${emu_log}" 2>&1
    rc_emu=$?
    set -e
    echo "[case $(printf '%03d' "${idx}")] emulator rc=${rc_emu} log=${emu_log}"
  fi

  if [[ "${AUTO_CONTINUE}" -eq 0 ]]; then
    read -r -p "Optional note for this case (SSSpeed/chip/io): " note
  fi

  end_ts="$(date -Iseconds)"
  {
    printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" \
      "$(printf '%03d' "${idx}")" \
      "${backend}" "${div}" "${wr}" "${rd}" \
      "${start_ts}" "${end_ts}" \
      "${rc_truth}" "${rc_buptest}" "${rc_emu}"
    printf "# note=%s\n" "${note}"
  } >> "${meta}"

  printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" \
    "$(printf '%03d' "${idx}")" \
    "${backend}" "${div}" "${wr}" "${rd}" \
    "${start_ts}" "${end_ts}" \
    "${rc_truth}" "${rc_buptest}" "${rc_emu}" \
    "$(csv_escape "${note}")" >> "${RESULTS_CSV}"
}

main() {
  local parsed
  local case_idx=1
  local backend
  local div
  local wr
  local rd

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --base-config) BASE_CFG="$2"; shift 2 ;;
      --kernel-only) BACKENDS=("kernel"); shift ;;
      --userspace-only) BACKENDS=("userspace"); shift ;;
      --userspace-divs)
        parsed="$(parse_csv_u32_list "$2")"
        read -r -a USER_DIVS <<< "${parsed}"
        shift 2
        ;;
      --userspace-wr)
        parsed="$(parse_csv_u32_list "$2")"
        read -r -a USER_WRS <<< "${parsed}"
        shift 2
        ;;
      --userspace-rd)
        parsed="$(parse_csv_u32_list "$2")"
        read -r -a USER_RDS <<< "${parsed}"
        shift 2
        ;;
      --no-truth) RUN_TRUTH=0; shift ;;
      --truth-samples) TRUTH_SAMPLES="$2"; shift 2 ;;
      --run-buptest) RUN_BUPTEST=1; shift ;;
      --buptest-kb) BUPTEST_KB="$2"; shift 2 ;;
      --no-emulator) RUN_EMULATOR=0; shift ;;
      --auto) AUTO_CONTINUE=1; shift ;;
      --continue-on-fail) FORCE_CONTINUE_ON_FAIL=1; shift ;;
      --emu-arg) EMU_EXTRA_ARGS+=("$2"); shift 2 ;;
      -h|--help) usage; exit 0 ;;
      *) die "Unknown option: $1" ;;
    esac
  done

  [[ -f "${BASE_CFG}" ]] || die "Base config not found: ${BASE_CFG}"
  [[ -x "${EMU_BIN}" ]] || die "Emulator binary not found/executable: ${EMU_BIN}"
  [[ -x "${TRUTH_BIN}" ]] || die "pistorm_truth_test binary not found/executable: ${TRUTH_BIN}"
  if [[ "${RUN_BUPTEST}" -eq 1 ]]; then
    [[ -x "${BUPTEST_BIN}" ]] || die "buptest binary not found/executable: ${BUPTEST_BIN}"
  fi

  mkdir -p "${RUN_DIR}"
  cat > "${RESULTS_CSV}" <<EOF
case,backend,gpclk_div,wr_stretch,rd_stretch,start_ts,end_ts,truth_rc,buptest_rc,emu_rc,note
EOF

  echo "Run directory: ${RUN_DIR}"
  echo "Base config: ${BASE_CFG}"
  echo "Backends: ${BACKENDS[*]}"
  echo "Userspace divs: ${USER_DIVS[*]}"
  echo "Userspace wr stretch: ${USER_WRS[*]}"
  echo "Userspace rd stretch: ${USER_RDS[*]}"
  echo "Truth test: ${RUN_TRUTH} samples=${TRUTH_SAMPLES}"
  echo "BUP test: ${RUN_BUPTEST} size_kb=${BUPTEST_KB}"
  echo "Launch emulator: ${RUN_EMULATOR}"
  echo

  for backend in "${BACKENDS[@]}"; do
    if [[ "${backend}" == "kernel" ]]; then
      run_case "${case_idx}" "kernel" "-" "-" "-"
      case_idx=$((case_idx + 1))
      continue
    fi

    for div in "${USER_DIVS[@]}"; do
      for wr in "${USER_WRS[@]}"; do
        for rd in "${USER_RDS[@]}"; do
          run_case "${case_idx}" "userspace" "${div}" "${wr}" "${rd}"
          case_idx=$((case_idx + 1))
        done
      done
    done
  done

  echo
  echo "Sweep complete."
  echo "Results CSV: ${RESULTS_CSV}"
}

main "$@"
